/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Server } from "./Server";
import { ServerCountArgs } from "./ServerCountArgs";
import { ServerFindManyArgs } from "./ServerFindManyArgs";
import { ServerFindUniqueArgs } from "./ServerFindUniqueArgs";
import { CreateServerArgs } from "./CreateServerArgs";
import { UpdateServerArgs } from "./UpdateServerArgs";
import { DeleteServerArgs } from "./DeleteServerArgs";
import { BotFindManyArgs } from "../../bot/base/BotFindManyArgs";
import { Bot } from "../../bot/base/Bot";
import { User } from "../../user/base/User";
import { ServerService } from "../server.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Server)
export class ServerResolverBase {
  constructor(
    protected readonly service: ServerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Server",
    action: "read",
    possession: "any",
  })
  async _serversMeta(
    @graphql.Args() args: ServerCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Server])
  @nestAccessControl.UseRoles({
    resource: "Server",
    action: "read",
    possession: "any",
  })
  async servers(@graphql.Args() args: ServerFindManyArgs): Promise<Server[]> {
    return this.service.servers(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Server, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Server",
    action: "read",
    possession: "own",
  })
  async server(
    @graphql.Args() args: ServerFindUniqueArgs
  ): Promise<Server | null> {
    const result = await this.service.server(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Server)
  @nestAccessControl.UseRoles({
    resource: "Server",
    action: "create",
    possession: "any",
  })
  async createServer(@graphql.Args() args: CreateServerArgs): Promise<Server> {
    return await this.service.createServer({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Server)
  @nestAccessControl.UseRoles({
    resource: "Server",
    action: "update",
    possession: "any",
  })
  async updateServer(
    @graphql.Args() args: UpdateServerArgs
  ): Promise<Server | null> {
    try {
      return await this.service.updateServer({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Server)
  @nestAccessControl.UseRoles({
    resource: "Server",
    action: "delete",
    possession: "any",
  })
  async deleteServer(
    @graphql.Args() args: DeleteServerArgs
  ): Promise<Server | null> {
    try {
      return await this.service.deleteServer(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Bot], { name: "bots" })
  @nestAccessControl.UseRoles({
    resource: "Bot",
    action: "read",
    possession: "any",
  })
  async findBots(
    @graphql.Parent() parent: Server,
    @graphql.Args() args: BotFindManyArgs
  ): Promise<Bot[]> {
    const results = await this.service.findBots(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: Server): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
